name: Preview DSG PDP Rewrite feature Playwright Tests
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  playwright:
    name: 'Preview DSG PDP Rewrite feature Playwright Tests'
    runs-on: [ self-hosted, azure ]
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          echo "Install dependencies from lock file"
          npm ci

          echo "Install Playwright and dependencies"
          npx playwright install --with-deps

      - name: Run tests with @rewrite tag
        run: npx playwright test --grep @rewrite
        env:
            ENV: dsg_preview

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 2