name: PROD All Secured Athlete Playwright Tests

on:
  schedule:
    - cron: '*/4 * * * *'  # Run every 4 minutes
  workflow_dispatch:

env:
  MENTIONS: jacob.jarosz@dcsg.com,punya.narra@dcsg.com
  WEB_HOOKS_URL: https://prod-190.westus.logic.azure.com:443/workflows/1101ef5f567542bdb2eb85bc992c1298/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=f7slGQG3iqjN6h2AiNVnIeEAv6tCcTeWkHo-x3-lZRM
  NOTIFY_ON_SUCCESS: false

jobs:
  playwright:
    name: 'PROD All Secured Athlete Playwright'
    runs-on: [ self-hosted, azure ]
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
        # with:
          # node-version: 20

      - name: Install Dependencies
        run: |
          echo "Install dependencies from lock file"
          npm ci

          echo "Install Playwright and dependencies"
          npx playwright install --with-deps

      - name: DSG - Run Login and Forgot PW tests
        run: |
          echo "Run login and forgot pw tests on DSG"
          npx playwright test secured_athlete_prod_tests.spec.ts
        env:
            ENV: dsg_prod    
          
      - name: Golf Galaxy - Run Login and Forgot PW tests
        run: |
          echo "Run login and forgot pw tests on GG"
          npx playwright test secured_athlete_prod_tests.spec.ts
        env:
            ENV: gg_prod

      - name: Public Lands - Run Login and Forgot PW tests
        run: |
          echo "Run login and forgot pw tests on PL"
          npx playwright test secured_athlete_prod_tests.spec.ts
        env:
            ENV: pl_prod 

      - name: Upload Report     
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 2`

      # - uses: actions/checkout@master
      - name: Microsoft Teams Alert Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          job: ${{ toJson(job) }}
          title: "{title: `** ALERT ** Failure in Secured Athlete Login Scripts`}"

      #View report
      - name: Publish CTRF Detailed Test Summary Results
        run: npx github-actions-ctrf tests ctrf/ctrf-report.json
        if: always()
    # View only failed summary report with Stack trace
      - name: Publish CTRF Failed Test Summary Results
        run: npx github-actions-ctrf failed ctrf/ctrf-report.json
        if: always()

      # - name: Push Results to Prometheus
        # run: |
          # curl -X POST -H "Content-Type: application/json" -d @ctrf/ctrf-report.json http://ubtu-cs-q-6085.dcsg.com/api/v1/import

         