name: Secured Athlete Playwright Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  playwright:
    name: 'Secured Athlete Playwright'
    runs-on: [ self-hosted, azure ]
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
        # with:
          # node-version: 20

      - name: Install Dependencies
        run: |
          echo "Install dependencies from lock file"
          npm ci

          echo "Install Playwright and dependencies"
          npx playwright install --with-deps

      - name: DSG - Run Login and Forgot PW tests
        run: |
          echo "Run login and forgot pw tests on DSG"
          npx playwright test
        env:
            ENV: dsg_prod    
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-DSG
          path: playwright-report/
          retention-days: 3`   
          
      - name: Golf Galaxy - Run Login and Forgot PW tests
        run: |
          echo "Run login and forgot pw tests on GG"
          npx playwright test
        env:
            ENV: gg_prod
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-GG
          path: playwright-report/
          retention-days: 3`

      - name: Public Lands - Run Login and Forgot PW tests
        run: |
          echo "Run login and forgot pw tests on PL"
          npx playwright test
        env:
            ENV: pl_prod      
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report-PL
          path: playwright-report/
          retention-days: 3`

      # - uses: actions/checkout@master
      - name: Microsoft Teams Alert Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          job: ${{ toJson(job) }}
          overwrite: "{title: `**Test ALERT** Failure in Secured Athlete Login Scripts`}"     

         