name: Secured Athlete Playwright Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  playwright:
    name: 'Secured Athlete Playwright'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run GG Tests
        run: |
          echo "Install dependencies from lock file"
          npm ci

          echo "Run login and forgot pw tests on GG"
          npm test

         