name: Secured Athlete Playwright Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  playwright:
    name: 'Secured Athlete Playwright'
    runs-on: [ self-hosted, azure ]
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
        # with:
          # node-version: 20

      - name: Install Dependencies
        run: |
          echo "Install dependencies from lock file"
          npm ci

        # echo "Install Playwright and dependencies"
        # npx playwright install --with-deps

      - name: Run Login and Forgot PW tests on GG
        run: |
          echo "Run login and forgot pw tests on GG"
          npx playwright test
        env:
            ENV: gg_prod

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3`

         